spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/couponsDb?serverTimezone=UTC&createDatabaseIfNotExist=true
    driver-class-userName: com.mysql.cj.jdbc.Driver
    password: '1234'
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: 'false'
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  jpa:
    hibernate:
      ddl-auto: create
  security:
    oauth2:
          resourceserver:
            jwt:
              issuer-uri: http://localhost:8180/realms/spring_coupons
          client:
            registration:
              keycloak:
                client-id: spring-app
                client-secret: wZ5twjGGzcn7DuBYWO8FdFoBn1o2T00B
                scope: openid, profile, email
                authorization-grant-type: authorization_code
                redirect-uri: "http://localhost:8080/login/oauth2/code/keycloak"
            provider:
              keycloak:
                issuer-uri: http://localhost:8180/realms/spring_coupons

sys:
  password: '1234'
  username: admin

server:
  port: 8080
